# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a1fd8138d574d9b6ada9002416c392109732c1bbcc516e5a2b20e0a482adf0a14163f10df397fbd237a1bf9f5b675c66537421da75c249ca005908bcc15616

test:
  secret_key_base: 4c6555bd039d8a7f721cb221b75152c34c728902ed9a9ff13938e01fdbf8474d2c424f1072f5318c9e3a147ad2b032381dde2d318786f0603cefe3bac58c011c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
